# Dev configuaration
#
image:
  tag: 0.9.3
  
replicaCount: 1

podAnnotations: 
  vault.hashicorp.com/agent-inject: 'true'
  vault.hashicorp.com/role: 'testserver'
  vault.hashicorp.com/agent-inject-secret-testsecret: 'local/data/testserver/testsecret'
  vault.hashicorp.com/agent-inject-template-testsecret: |
    {{- with secret "local/data/testserver/testsecret" -}}
    {{ .Data.data.secret }}
    {{- end -}


env:
  - name: SECRET_FILE
    value: "/vault/secrets/testsecret"
  - name: FLASK_ENV
    value: 'Test'

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: testserver
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: testserver
              port:
                number: 80
