# Dev configuaration
#
environment: demo

image:
  tag: 0.9.3
  
replicaCount: 1

podAnnotations: 
  vault.hashicorp.com/agent-inject: 'true'
  vault.hashicorp.com/role: 'testserver'
  vault.hashicorp.com/agent-inject-secret-testsecret: 'local/data/testserver/secret'
  vault.hashicorp.com/agent-inject-template-testsecret: |
    {{- with secret "local/data/testserver/secret" -}}
    {{ .Data.data.secret }}
    {{- end -}


env:
  - name: SECRET_FILE
    value: "/vault/secrets/testsecret"
  - name: FLASK_ENV
    value: 'Demo'

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: testserver
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: testserver
              port:
                number: 80

networkPolicy:
  create: true

  cilium:
        ingress:
          Endpoints:
            - labels:
                - testserver
              ports:
                - 80

        egress:
          CIDRSets:
            - cidrs:
                - "10.27.31.128/32"
              ports:
                - 5671
          Endpoints:
            - labels:
                - redis
              ports:
                - 8080
            - labels:
                - vault-agent-injector
              ports:
                - 8080
            - labels:
                - vault
              ports:
                - 8200
          FQDNs:
            - names:
                - mysql.gerull.nl
              ports:
                - 3306
            - names:
                - galaxy.ansible.com
                - ansible-galaxy.s3.amazonaws.com
              ports:
                - 443
