# Dev configuaration
#
image:
  tag: 0.9.6
  
replicaCount: 1

podAnnotations: 
  vault.hashicorp.com/agent-inject: 'true'
  vault.hashicorp.com/role: 'testserver'
  vault.hashicorp.com/agent-inject-secret-testsecret: 'local/data/testserver/secret'
  vault.hashicorp.com/agent-inject-template-testsecret: |
    {{- with secret "local/data/testserver/secret" }}
    {{ .Data.data.secret }}
    {{- end }}

env:
  - name: SECRET_FILE
    value: "/vault/secrets/testsecret"
  - name: FLASK_ENV
    value: 'Dev'
  - name: REDIS_SERVER
    value: redis/redis.svc

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    # traefik.ingress.kubernetes.io/router.middlewares: testserver-testserver-stripprefix@kubernetescrd
  hosts:
    - host: testserver.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: testserver
              port:
                number: 80

networkPolicy:
  create: false