apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: testserver-local
    namespace: argocd
  spec:
    project: default
    destination:
      namespace: dev-local
      server: https://kubernetes.default.svc
    source:
      path: kubernetes/dev-local
      repoURL: https://github.com/cgerull/deploy-test-server
      targetRevision: localtest
    syncPolicy:
      automated: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
