---
{{- if .Values.networkPolicy.create -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: vault
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: vault
  ingress:
    {{- if or (eq (.Values.environment | lower) "development") (eq (.Values.environment | lower) "test") }}
    # - fromEndpoints:
    #     - matchLabels:
    #         io.kubernetes.pod.namespace: tp-gitlab-runner
    - fromEndpoints:
        - {}
      toPorts:
        - ports:
            - port: "8200"
    {{- end }}
    {{- if .Values.networkPolicy.cilium.ingress }}
    {{- range .Values.networkPolicy.cilium.ingress.Endpoints }}
    - fromEndpoints:
        {{- range .labels }}
        - matchLabels:
{{ toYaml . | indent 12 }}
        {{- end }}
      toPorts:
        - ports:
        {{- range .ports }}
            - port: {{ . | quote }}
        {{- end }}
    {{- end }}
    {{- end }}
  egress:
    - {}
{{- end -}}
