{{- if .Values.mysql.enabled }}
{{- if .Values.mysql.networkPolicy.create -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: mysql
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: mysql
  ingress:
    {{- if or (eq (.Values.global.environment | lower) "development") (eq (.Values.global.environment | lower) "test") }}
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: tp-gitlab-runner
    {{- end }}
    - fromEndpoints:
        - {}
      toPorts:
        - ports:
            - port: "3306"
    {{- if .Values.mysql.networkPolicy.cilium.ingress }}
    {{- range .Values.mysql.networkPolicy.cilium.ingress.Endpoints }}
    - fromEndpoints:
        {{- range .labels }}
        - matchLabels:
{{ toYaml . | indent 12 }}
        {{- end }}
      toPorts:
        - ports:
        {{- range .ports }}
            - port: {{ . | quote }}
        {{- end }}
    {{- end }}
    {{- end }}
  egress:
    - {}
{{- end -}}
{{- end -}}
